GET http://localhost:3003

###
POST http://localhost:3003/user
Content-Type: application/json

{
	"name": "Osmar Azevedo dos Santos",
	"nickname": "Mazinho",
	"email": "osmarnwe@dev.com"
}

###

GET http://localhost:3003/user/1626989612542

###
PUT http://localhost:3003/user/edit/1626989612542
Content-Type: application/json

{
    "name": "Bianca atualizado 4",
    "nickname": "Bianca",
    "email": "novoemail@gmail.com"
}